name: Cypress Tests

on: [push]

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4.1.4

    - name: Install dependencies
      run: npx install

    - name: Run E2E tests
    - run: npx cypress run
